# Generated by Django 4.2.6 on 2023-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=155)),
                ('lastname', models.TextField(max_length=155)),
                ('email', models.TextField(max_length=155)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
