# Generated by Django 4.2.6 on 2023-12-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_confirmation', '0002_alter_register_table_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register_table',
            name='phone',
        ),
    ]
